### ISSUE TITLE
Queries to insert data from a sub-query are not well formed

### ISSUE THREAD

**Issue by Lonnytunes** [pounard/goat-query#15]
The incriminated line is this one:
https://github.com/pounard/goat-query/blob/77ddb01e6a83fd2061cb78218052fc6bf5ee3eec/src/Query/Writer/DefaultFormatter.php#L694

I think it should be only `(%s)`.

**Comment by pounard** [comment]
Nice, I'll write some tests around it.

**Comment by pounard** [comment]
Merci l'ami !
