### ISSUE TITLE
Method renaming suggestions

### ISSUE THREAD

**Issue by Lonnytunes** [pounard/goat-query#23]
Here are my propositions:

- rename `condition()` to `where()` to be closer to the SQL terms;
- rename `expression()` to `whereExpression()` to be consistent with `columnExpression()` and `havingExpression()` methods (I firstly thought `expression()` was the method to use to do what `columnExpression()` does).

As well, I wonder if it would not be better to rename the `Where` class to `Condition` for a more generic term completely dissociated from the place the condition will finally have in the query.

**Comment by pounard** [comment]
All those renames seems sane, it'll be for 2.0 !

As for renaming the Where object, I'm not sure, a few other frameworks kept that name as well.

**Comment by pounard** [comment]
Done in 2.x, needs backport to 1.x yet.

**Comment by pounard** [comment]
Backported in 1.x, thanks @Lonnytunes !
